"""
This code creates an image manipulation application using the PyQt5 library.
It also uses image manipulation libraries such as skimage, matplotlib, and PIL.
These code blocks are compiled to create interfaces.
"""

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys

from PyQt5.QtWidgets import QApplication, QMainWindow, QAction, QTextEdit, QVBoxLayout, QWidget, QPushButton, QUndoStack


import matplotlib.pyplot as plt
from skimage import data, img_as_float
from skimage.segmentation import chan_vese
from skimage import io, color, segmentation
from skimage.filters import threshold_multiotsu
from skimage import data, img_as_float
from skimage.segmentation import (morphological_chan_vese,morphological_geodesic_active_contour,inverse_gaussian_gradient,checkerboard_level_set)
from skimage.morphology import disk, binary_opening
from skimage import filters
from skimage.util import compare_images
from PIL import Image
import skimage
import pylab as plt
import numpy as np
import cv2
import matplotlib.image as mpimg
import colorsys
import matplotlib.pyplot as plt
from skimage import data
from skimage.color import *
from skimage import io, color
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 892)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/icons8-edit-image-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_20.setObjectName("gridLayout_20")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem, 0, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButton_S1 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_S1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/icons8-opened-folder-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_S1.setIcon(icon1)
        self.toolButton_S1.setObjectName("toolButton_S1")
        self.verticalLayout.addWidget(self.toolButton_S1)
        self.toolButton_S3 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_S3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/icons8-broom-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_S3.setIcon(icon2)
        self.toolButton_S3.setObjectName("toolButton_S3")
        self.verticalLayout.addWidget(self.toolButton_S3)
        self.toolButton_S2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_S2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/icons8-export-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_S2.setIcon(icon3)
        self.toolButton_S2.setObjectName("toolButton_S2")
        self.verticalLayout.addWidget(self.toolButton_S2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolButton_O1 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_O1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/icons8-save-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_O1.setIcon(icon4)
        self.toolButton_O1.setObjectName("toolButton_O1")
        self.verticalLayout_2.addWidget(self.toolButton_O1)
        self.toolButton_O2 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_O2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/icons8-save-as-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_O2.setIcon(icon5)
        self.toolButton_O2.setObjectName("toolButton_O2")
        self.verticalLayout_2.addWidget(self.toolButton_O2)
        self.toolButton_O3 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_O3.setText("")
        self.toolButton_O3.setIcon(icon3)
        self.toolButton_O3.setObjectName("toolButton_O3")
        self.verticalLayout_2.addWidget(self.toolButton_O3)
        self.toolButton_O4 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_O4.setText("")
        self.toolButton_O4.setIcon(icon2)
        self.toolButton_O4.setObjectName("toolButton_O4")
        self.verticalLayout_2.addWidget(self.toolButton_O4)
        self.toolButton_O6 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_O6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/icons8-redo-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_O6.setIcon(icon6)
        self.toolButton_O6.setObjectName("toolButton_O6")
        self.verticalLayout_2.addWidget(self.toolButton_O6)
        self.toolButton_O5 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_O5.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/icons8-undo-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_O5.setIcon(icon7)
        self.toolButton_O5.setObjectName("toolButton_O5")
        self.verticalLayout_2.addWidget(self.toolButton_O5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolButton_C1 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_C1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/icons8-color-mode-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_C1.setIcon(icon8)
        self.toolButton_C1.setObjectName("toolButton_C1")
        self.verticalLayout_3.addWidget(self.toolButton_C1)
        self.toolButton_C2 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_C2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icons/icons8-color-mode-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_C2.setIcon(icon9)
        self.toolButton_C2.setObjectName("toolButton_C2")
        self.verticalLayout_3.addWidget(self.toolButton_C2)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolButton_Seg1 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_Seg1.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Icons/icons8-image-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Seg1.setIcon(icon10)
        self.toolButton_Seg1.setObjectName("toolButton_Seg1")
        self.verticalLayout_4.addWidget(self.toolButton_Seg1)
        self.toolButton_Seg2 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_Seg2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Icons/icons8-image-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Seg2.setIcon(icon11)
        self.toolButton_Seg2.setObjectName("toolButton_Seg2")
        self.verticalLayout_4.addWidget(self.toolButton_Seg2)
        self.toolButton_Seg3 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_Seg3.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Icons/icons8-image-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Seg3.setIcon(icon12)
        self.toolButton_Seg3.setObjectName("toolButton_Seg3")
        self.verticalLayout_4.addWidget(self.toolButton_Seg3)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolButton_E1 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_E1.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Icons/icons8-r-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_E1.setIcon(icon13)
        self.toolButton_E1.setObjectName("toolButton_E1")
        self.verticalLayout_5.addWidget(self.toolButton_E1)
        self.toolButton_E2 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_E2.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Icons/icons8-s-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_E2.setIcon(icon14)
        self.toolButton_E2.setObjectName("toolButton_E2")
        self.verticalLayout_5.addWidget(self.toolButton_E2)
        self.toolButton_E3 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_E3.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Icons/icons8-scratch-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_E3.setIcon(icon15)
        self.toolButton_E3.setObjectName("toolButton_E3")
        self.verticalLayout_5.addWidget(self.toolButton_E3)
        self.toolButton_E4 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_E4.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Icons/icons8-paragraph-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_E4.setIcon(icon16)
        self.toolButton_E4.setObjectName("toolButton_E4")
        self.verticalLayout_5.addWidget(self.toolButton_E4)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setMinimumSize(QtCore.QSize(800, 0))
        self.groupBox_12.setMaximumSize(QtCore.QSize(800, 16777215))
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_19.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_Source = QtWidgets.QLabel(self.groupBox_12)
        self.label_Source.setText("")
        self.label_Source.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Source.setObjectName("label_Source")
        self.gridLayout_19.addWidget(self.label_Source, 0, 0, 1, 1)
        self.verticalLayout_22.addWidget(self.groupBox_12)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(800, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(800, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_Output = QtWidgets.QLabel(self.groupBox_6)
        self.label_Output.setText("")
        self.label_Output.setObjectName("label_Output")
        self.gridLayout_6.addWidget(self.label_Output, 0, 0, 1, 1)
        self.verticalLayout_22.addWidget(self.groupBox_6)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_22)
        self.gridLayout_20.addLayout(self.formLayout, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem3, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 758, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Export_As = QtWidgets.QMenu(self.menu_File)
        self.menu_Export_As.setIcon(icon3)
        self.menu_Export_As.setObjectName("menu_Export_As")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Clear = QtWidgets.QMenu(self.menu_Edit)
        self.menu_Clear.setIcon(icon2)
        self.menu_Clear.setObjectName("menu_Clear")
        self.menu_Conversion = QtWidgets.QMenu(self.menubar)
        self.menu_Conversion.setObjectName("menu_Conversion")
        self.menu_Segmentation = QtWidgets.QMenu(self.menubar)
        self.menu_Segmentation.setObjectName("menu_Segmentation")
        self.menu_Edge_Detection = QtWidgets.QMenu(self.menubar)
        self.menu_Edge_Detection.setObjectName("menu_Edge_Detection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open_Source = QtWidgets.QAction(MainWindow)
        self.action_Open_Source.setObjectName("action_Open_Source")
        self.action_Save_Output = QtWidgets.QAction(MainWindow)
        self.action_Save_Output.setCheckable(True)
        self.action_Save_Output.setEnabled(False)
        self.action_Save_Output.setIcon(icon4)
        self.action_Save_Output.setObjectName("action_Save_Output")
        self.action_save_As_Output = QtWidgets.QAction(MainWindow)
        self.action_save_As_Output.setCheckable(True)
        self.action_save_As_Output.setEnabled(False)
        self.action_save_As_Output.setIcon(icon5)
        self.action_save_As_Output.setObjectName("action_save_As_Output")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Source = QtWidgets.QAction(MainWindow)
        self.action_Source.setCheckable(True)
        self.action_Source.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Icons/icons8-input-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Source.setIcon(icon17)
        self.action_Source.setObjectName("action_Source")
        self.action_Output = QtWidgets.QAction(MainWindow)
        self.action_Output.setCheckable(True)
        self.action_Output.setEnabled(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Icons/icons8-output-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Output.setIcon(icon18)
        self.action_Output.setObjectName("action_Output")
        self.action_Undo_Output = QtWidgets.QAction(MainWindow)
        self.action_Undo_Output.setCheckable(True)
        self.action_Undo_Output.setEnabled(False)
        self.action_Undo_Output.setIcon(icon7)
        self.action_Undo_Output.setObjectName("action_Undo_Output")
        self.action_Redo_Output = QtWidgets.QAction(MainWindow)
        self.action_Redo_Output.setCheckable(True)
        self.action_Redo_Output.setEnabled(False)
        self.action_Redo_Output.setIcon(icon6)
        self.action_Redo_Output.setObjectName("action_Redo_Output")
        self.action_Source_2 = QtWidgets.QAction(MainWindow)
        self.action_Source_2.setCheckable(True)
        self.action_Source_2.setEnabled(False)
        self.action_Source_2.setIcon(icon17)
        self.action_Source_2.setObjectName("action_Source_2")
        self.actionO_Output = QtWidgets.QAction(MainWindow)
        self.actionO_Output.setCheckable(True)
        self.actionO_Output.setEnabled(False)
        self.actionO_Output.setIcon(icon18)
        self.actionO_Output.setObjectName("actionO_Output")
        self.action_RGB_to_Grayscale = QtWidgets.QAction(MainWindow)
        self.action_RGB_to_Grayscale.setCheckable(True)
        self.action_RGB_to_Grayscale.setEnabled(False)
        self.action_RGB_to_Grayscale.setIcon(icon8)
        self.action_RGB_to_Grayscale.setObjectName("action_RGB_to_Grayscale")
        self.action_RGB_to_HSV = QtWidgets.QAction(MainWindow)
        self.action_RGB_to_HSV.setCheckable(True)
        self.action_RGB_to_HSV.setEnabled(False)
        self.action_RGB_to_HSV.setIcon(icon9)
        self.action_RGB_to_HSV.setObjectName("action_RGB_to_HSV")
        self.action_Multi_Otsu_Thresholding = QtWidgets.QAction(MainWindow)
        self.action_Multi_Otsu_Thresholding.setCheckable(True)
        self.action_Multi_Otsu_Thresholding.setEnabled(False)
        self.action_Multi_Otsu_Thresholding.setIcon(icon10)
        self.action_Multi_Otsu_Thresholding.setObjectName("action_Multi_Otsu_Thresholding")
        self.action_Chan_Vese_Segmentation = QtWidgets.QAction(MainWindow)
        self.action_Chan_Vese_Segmentation.setCheckable(True)
        self.action_Chan_Vese_Segmentation.setEnabled(False)
        self.action_Chan_Vese_Segmentation.setIcon(icon11)
        self.action_Chan_Vese_Segmentation.setObjectName("action_Chan_Vese_Segmentation")
        self.action_Morphological_Snakes = QtWidgets.QAction(MainWindow)
        self.action_Morphological_Snakes.setCheckable(True)
        self.action_Morphological_Snakes.setEnabled(False)
        self.action_Morphological_Snakes.setIcon(icon12)
        self.action_Morphological_Snakes.setObjectName("action_Morphological_Snakes")
        self.action_Roberts = QtWidgets.QAction(MainWindow)
        self.action_Roberts.setCheckable(True)
        self.action_Roberts.setEnabled(False)
        self.action_Roberts.setIcon(icon13)
        self.action_Roberts.setObjectName("action_Roberts")
        self.action_Sobel = QtWidgets.QAction(MainWindow)
        self.action_Sobel.setCheckable(True)
        self.action_Sobel.setEnabled(False)
        self.action_Sobel.setIcon(icon14)
        self.action_Sobel.setObjectName("action_Sobel")
        self.action_Scharr = QtWidgets.QAction(MainWindow)
        self.action_Scharr.setCheckable(True)
        self.action_Scharr.setEnabled(False)
        self.action_Scharr.setIcon(icon15)
        self.action_Scharr.setObjectName("action_Scharr")
        self.action_Prewitt = QtWidgets.QAction(MainWindow)
        self.action_Prewitt.setCheckable(True)
        self.action_Prewitt.setEnabled(False)
        self.action_Prewitt.setIcon(icon16)
        self.action_Prewitt.setObjectName("action_Prewitt")
        self.menu_Export_As.addAction(self.action_Source)
        self.menu_Export_As.addAction(self.action_Output)
        self.menu_File.addAction(self.action_Open_Source)
        self.menu_File.addAction(self.action_Save_Output)
        self.menu_File.addAction(self.action_save_As_Output)
        self.menu_File.addAction(self.menu_Export_As.menuAction())
        self.menu_File.addAction(self.action_Exit)
        self.menu_Clear.addAction(self.action_Source_2)
        self.menu_Clear.addAction(self.actionO_Output)
        self.menu_Edit.addAction(self.menu_Clear.menuAction())
        self.menu_Edit.addAction(self.action_Undo_Output)
        self.menu_Edit.addAction(self.action_Redo_Output)
        self.menu_Conversion.addAction(self.action_RGB_to_Grayscale)
        self.menu_Conversion.addAction(self.action_RGB_to_HSV)
        self.menu_Segmentation.addAction(self.action_Multi_Otsu_Thresholding)
        self.menu_Segmentation.addAction(self.action_Chan_Vese_Segmentation)
        self.menu_Segmentation.addAction(self.action_Morphological_Snakes)
        self.menu_Edge_Detection.addAction(self.action_Roberts)
        self.menu_Edge_Detection.addAction(self.action_Sobel)
        self.menu_Edge_Detection.addAction(self.action_Scharr)
        self.menu_Edge_Detection.addAction(self.action_Prewitt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Conversion.menuAction())
        self.menubar.addAction(self.menu_Segmentation.menuAction())
        self.menubar.addAction(self.menu_Edge_Detection.menuAction())
        
        
  
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Processing Application"))
        self.groupBox.setTitle(_translate("MainWindow", "Source"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Conversion"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Segmentation"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Edge Detection"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Source"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Output"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Export_As.setTitle(_translate("MainWindow", "&Export As"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menu_Clear.setTitle(_translate("MainWindow", "&Clear"))
        self.menu_Conversion.setTitle(_translate("MainWindow", "&Conversion"))
        self.menu_Segmentation.setTitle(_translate("MainWindow", "&Segmentation"))
        self.menu_Edge_Detection.setTitle(_translate("MainWindow", "&Edge Detection"))
        self.action_Open_Source.setText(_translate("MainWindow", "&Open Source"))
        self.action_Open_Source.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Save_Output.setText(_translate("MainWindow", "&Save Output"))
        self.action_save_As_Output.setText(_translate("MainWindow", "&Save As Output"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Shift+F4"))
        self.action_Source.setText(_translate("MainWindow", "&Source"))
        self.action_Output.setText(_translate("MainWindow", "&Output"))
        self.action_Undo_Output.setText(_translate("MainWindow", "&Undo Output"))
        self.action_Undo_Output.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.action_Redo_Output.setText(_translate("MainWindow", "&Redo Output"))
        self.action_Redo_Output.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_Source_2.setText(_translate("MainWindow", "&Source"))
        self.action_Source_2.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionO_Output.setText(_translate("MainWindow", "&Output"))
        self.actionO_Output.setShortcut(_translate("MainWindow", "Ctrl+Shift+L"))
        self.action_RGB_to_Grayscale.setText(_translate("MainWindow", "&RGB to Grayscale"))
        self.action_RGB_to_HSV.setText(_translate("MainWindow", "&RGB to HSV"))
        self.action_Multi_Otsu_Thresholding.setText(_translate("MainWindow", "&Multi-Otsu Thresholding"))
        self.action_Chan_Vese_Segmentation.setText(_translate("MainWindow", "&Chan-Vese Segmentation"))
        self.action_Morphological_Snakes.setText(_translate("MainWindow", "&Morphological Snakes"))
        self.action_Roberts.setText(_translate("MainWindow", "&Roberts"))
        self.action_Sobel.setText(_translate("MainWindow", "&Sobel"))
        self.action_Scharr.setText(_translate("MainWindow", "&Scharr"))
        self.action_Prewitt.setText(_translate("MainWindow", "&Prewitt"))



     



   